# Generated by Django 2.2 on 2019-04-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productimage_thumbnail'),
    ]

    operations = [
    ]
